### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by beuchelt** [info-sharing-environment/NIEM-Modeling-Tool#2]
Could you please add some basic installation instructions.

**Comment by timezra** [comment]
I will write up instructions this weekend. For now, I believe that you can use the project to build the project if you have access to the full distribution in dropbox. The only dependency that might be missing from there is m2e (maven for eclipse).

**Comment by beuchelt** [comment]
Tim, 

Thanks a lot. Will look later this week!

Best, 

Gerald

**Comment by timezra** [comment]
Hi Gerald,
I have added a file called "HowToBuild.md" to the root of the project. It contains instructions for building the project from source and for importing it into your Eclipse workspace.
Let me know if this helps.
Thanks,
---Tim---

**Comment by beuchelt** [comment]
Tim - 

I recommend you add in the Build description that folks set the MAVEN_OPTS to “-Xmx512m -XX:MaxPermSize=128m” 

Needed that to get past an out of memory heap error. 

Also right now the tests fail… will update you later. 

Best, 

Gerald

**Comment by timezra** [comment]
Hi Gerald,
Thank you for the update. I will update the doc with the suggested maven opts - strangely, I do not appear to have any problems with the default settings on Linux. Are you using windows by chance?
Also, are you running the tests from the workbench or from maven? I, too, seem to be having an issue running from a completely new install of the eclipse workbench but am not having an issue running the tests from maven, which leads me to think that the failure might be caused by a plug-in upgrade.
I will continue to look into this.
Thanks,
---Tim---

**Comment by beuchelt** [comment]
Hi Tim - 

It is a fresh Maven install on a Mac 10.9 system. I needed these options, because it would otherwise fail with the heap OOM error. The options are fixing this, but now I get an error 1 from the Mojo plugin during the uml tests. Will let you know what I find out. 

Best, 

Gerald
