### ISSUE TITLE
Importing MPD and extending problem

### ISSUE THREAD

**Issue by cabralje** [info-sharing-environment/NIEM-Modeling-Tool#4]
When you import an existing MPD the information models for each schema are named based on the MPD catalog.  The NIEM Modeling Tool has a defined way of naming information models and the schemas may be (usually will be) different from the naming in the MPD catalog.  If you use the NIEM Modeling Tool to add additional elements to an existing subset schema, the tool does not recognize that the information model for that schema already exists and you will end up with a second, different set of information models for the same schemas.
![screenshot](https://cloud.githubusercontent.com/assets/3745856/2854545/4ceca234-d152-11e3-948a-af73cf4bd7a5.png)

**Comment by timezra** [comment]
I have checked-in a fix for this and would appreciate any feedback you could give for it. The fix uses the targetNamespace instead of the package name to resolve reference library Information Models. This means that existing information models and their contained elements should be resolved correctly when you extend an imported MPD. One caveat, though. If you bring in reference library elements that are contained in other information models (say, you were importing a maritime-specific MPD and then extending it with elements contained in the fbi Information Model which was not already imported), then the new Information Model will follow the current convention (e.g., naming the Information Model fbiSubset and putting it in the PIM root rather than XMLSchemas::subsets::niem...::fbi).

Is this implementation acceptable enough to close out this issue?

Is there a singular, more standard way that we should be structuring our MPDs in the tool (the current structure was inferred from an earlier version of the PetAdoption example, but that example has changed since work on the tool started)?

Thanks for reporting this issue, and let me now if there is anything else that you find.
---Tim---

**Comment by cabralje** [comment]
Your solution sounds like it should work for the majority of cases.  I can test it with the next release.

I'm curious, though - why not consistently use the namespace uri to resolve information models, whether imported or extended?  That would solve the issue 100% of the time, right?

**Comment by timezra** [comment]
We are now using the namespace uri to resolve information models.
