### ISSUE TITLE
Renaming a Subset Class

### ISSUE THREAD

**Issue by eric-jahn** [info-sharing-environment/NIEM-Modeling-Tool#5]
In the 2012 NIEM Modeling guide, they show how a subseted type can be given a different name from the type that was subseted.  This is especially nice to use for the PIM representation of the model.  Here's an example from that guide showing how the nc:ActivityType was subseted and renamed "Activity".

![adoption](https://cloud.githubusercontent.com/assets/4115079/2986037/fe796084-dc40-11e3-8e32-df67c1c6fbea.png)

I'm trying to use the tool to do the same thing with this tool, but if I try to rename it as anything other than the selected "ActivityType" it won't allow me to save the newly renamed object.  I'm forced to escape out and keep the original preselected name as shown here:  

![my_activity](https://cloud.githubusercontent.com/assets/4115079/2986179/0e32a85e-dc42-11e3-8253-7ae479c6d681.png)

In my extension model, I plan to then inherit from these types.

**Comment by aowen** [comment]
Thanks for the question Eric.  Can you please clarify what you mean when you say “subset”.  Both the NIEM world and the UML world have different meanings for “subset”. The UML concept of subsetting in very similar to the NIEM/XML concept of substitution groups whereas NIEM subsetting when you create your own version (term used loosely) of a NIEM reference schema/package.  I believe you are using the term “subset” in the NIEM sense, but please confirm that.

If you want the ability to rename model elements in the NIEM reference models, you will need to go into the Eclipse preferences, then select NIEM UML and go into the Class Diagrams set of preferences and uncheck the option for “Restrict NIEM subsets to contain only content from NIEM Reference UML Model”.  You just need to be careful with this approach.  For example, if you rename “ActivityType” to “Activity” the resulting XML schema will be fine but if you rename “ActvityType” to “Foo”, the resulting NIEM core schema will contain a type called “FooType” which is not a valid NIEM core type.

It appears that you attached a graphic but that did not come through in this e-mail.

Thanks,
-Andrew
916.215.3933

**Comment by eric-jahn** [comment]
Andrew,
Sorry, yes, I did mean "subset" in the sense of a NIEM Core schema subset, not in the UML sense.  Okay, I'll check that option.  I noticed the renaming has to be done within the UML properties view, not in the class diagram object itself, but that is aok.  Thank you!  Yeah, github markdown doesn't render well in my email always either.  I'll close this case.

**Comment by timezra** [comment]
This is an interesting one and it raises an issue that we might want to address in the backlog: treating NIEM subsetted elements named like Activity as equivalent to elements named like ActivityType. If you import ActivityType with a couple of properties, then rename it to Activity, its properties will be removed (because Activity is considered different from ActivityType). Then, if you right click on the Activity element and try to Update Subset, you will not get a Dialog to pop up because the tool does not resolve Activity as ActivityType. Also, if you change the name ActivityType to Activity in an external tool, then try to re-import an ActivityType, a second ActivityType element will be created in the subset.
I think we should probably re-open this one.
---Tim---

**Comment by aowen** [comment]
Good point Tim – this should remain an open item.

What would the enhancement look like for this?  Would it be as straightforward as saying two classes with the names “x” and “xType” are actually the same class?  So, if a single package defines class “x” and “xType”, we’d expect to see a warning in the Eclipse problems view indicating that the classes are no distinguishable.  Does this sound about right?

Thanks,
-Andrew
916.215.3933

**Comment by eric-jahn** [comment]
I think it should be more general than just allowing for the "Type" suffix
to be dropped . I should be able to rename it to anything not just removing
the suffix. So I think it needs to be mapped on a specific class basis and
remembered.

**Comment by timezra** [comment]
Making [...]Type names and [...] names equivalent sounds like it would address this
immediate need. I have a strong feeling there are other equivalencies, as
well, and will need to check the spec on it.
One more question: would this rule apply to all packages in the PIM, not
just subsets, since the PSM transformation normalizes these names by
appending the 'Type' suffix?

As for mapping any class name to the NIEM subset class name, I would wonder
if this kind of name dereferencing might get unwieldy for end users.

---Tim---

On Thu, May 15, 2014 at 10:04 AM, Andrew Owen notifications@github.comwrote:

> Good point Tim – this should remain an open item.
> 
> What would the enhancement look like for this? Would it be as
> straightforward as saying two classes with the names “x” and “xType” are
> actually the same class? So, if a single package defines class “x” and
> “xType”, we’d expect to see a warning in the Eclipse problems view
> indicating that the classes are no distinguishable. Does this sound about
> right?
> 
> Thanks,
> -Andrew
> 916.215.3933
> 
> From: Tim Myer [mailto:notifications@github.com]
> Sent: Thursday, May 15, 2014 11:55 AM
> To: info-sharing-environment/NIEM-Modeling-Tool
> Cc: Andrew Owen
> Subject: Re: [NIEM-Modeling-Tool] Renaming a Subset Class (#5)
> 
> This is an interesting one and it raises an issue that we might want to
> address in the backlog: treating NIEM subsetted elements named like
> Activity as equivalent to elements named like ActivityType. If you import
> ActivityType with a couple of properties, then rename it to Activity, its
> properties will be removed (because Activity is considered different from
> ActivityType). Then, if you right click on the Activity element and try to
> Update Subset, you will not get a Dialog to pop up because the tool does
> not resolve Activity as ActivityType. Also, if you change the name
> ActivityType to Activity in an external tool, then try to re-import an
> ActivityType, a second ActivityType element will be created in the subset.
> I think we should probably re-open this one.
> ---Tim---
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/info-sharing-environment/NIEM-Modeling-Tool/issues/5#issuecomment-43228154>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/info-sharing-environment/NIEM-Modeling-Tool/issues/5#issuecomment-43237039
> .

## 

http://timezra.blogspot.com

**Comment by aowen** [comment]
Doing that remembering within the tool might work, but what about sharing models between tools?  If I rename NIEM core PersonType to Blah and then open the model in another tool, I don’t believe the profile offers a way to convey that class Blah is really PersonType in NIEM core.

At the PIM layer, all NIEM classes are represented as UML classes which are identified within a package by their name.  I don’t believe there is a way to give the class a name that displays in the diagram then a different, persistent name, that uniquely identifies the class to allow it to always represent the same NIEM class, regardless of the displayed name.  We can look into this…

-Andrew
916.215.3933

**Comment by eric-jahn** [comment]
But my pim niem core subset  has a fully qualified namespace, so shouldn't
my renamed types be conveyed with my new subset namespace?  The fully
qualified namespace origin of each of its contained properties would also
be preserved within the renamed type, so there would be no confusion where
they originally came from.  Just a thought.   -Eric

Eric Jahn
Data Architect/IT Director
Alexandria Consulting LLC
St. Petersburg, Florida
727.537.9474
alexandriaconsulting.com

**Comment by aowen** [comment]
That part is fine, but when it comes time to do a transformation to NIEM schema, how will the tool know that Blah, in NIEM core, should actually be PersonType in NIEM core when the tool produces schema?

Thanks,
-Andrew
916.215.3933

**Comment by eric-jahn** [comment]
Would it need to know?  It just needs to know where all its sub-properties
came from (which point to PersonType).

Eric Jahn
Data Architect/IT Director
Alexandria Consulting LLC
St. Petersburg, Florida
727.537.9474
alexandriaconsulting.com

**Comment by aowen** [comment]
Not sure I understand why you mean by pointing to PersonType, can you clarify? I do think we’re onto a good feature here, but I want to make sure it is something that would work within the bounds of the profile.

-Andrew
916.215.3933

**Comment by eric-jahn** [comment]
Andrew, sorry, by "point to", I mean "fully qualified".  To rephrase the
sentence completely: "The schema producing tool just needs to know where
all the renamed class' sub-properties came from (which are fully qualified
as the nc:PersonType).

As I'm currently using the NIEM Modeling Tool, I'm also restricting the
properties of inherited classes of  the one I'm renaming, so it's really a
different class than the original niem core class I renamed.  So for
example, my renamed nc:ProgramType doesn't inherit all the nc:ActivityType
properties, so it's not really a full nc:ProgramType anymore, and should be
distinguishable from one.

Eric Jahn
Data Architect/IT Director
Alexandria Consulting LLC
St. Petersburg, Florida
727.537.9474
alexandriaconsulting.com

**Comment by aowen** [comment]
Your first paragraph assumes encapsulation, which isn’t the case in NIEM.  All elements/properties are globally accessible in NIEM, so just because a type contains PersonName, it would be risky to assume that the containing type is PersonType.

Could you send me an email with a screenshot of the scenario you describe with ProgramType and ActivityType?

-Andrew
916.215.3933

**Comment by eric-jahn** [comment]
![example](https://cloud.githubusercontent.com/assets/4115079/2990916/dcf39c6e-dc76-11e3-8771-523aee4f9e9b.png)
Andrew, with the first part. I would use qualified namespaces on the
contained properties of the renamed type to explicitly state where they
originate.  I agree on not inferring types.  I attached a screenshot of the
Program/Activity types.    -Eric

Eric Jahn
Data Architect/IT Director
Alexandria Consulting LLC
St. Petersburg, Florida
727.537.9474
alexandriaconsulting.com

**Comment by dlacy27** [comment]
Hi Eric:

  I'm new to the NIEM UML tool & to SEARCH, but my question is, what is the high-level business need, the rationale, to create another name/equivalent for a NIEM class? What need does it serve?

 I generally ascribe to not messing with nc:; but if necessary, how would you describe that need to a user, under what circumstances?
- Diane

Diane Lacy
Information Sharing Specialist
SEARCH, The National Consortium for Justice Information and Statistics
(541) 499-8610  /  dlacy@search.orgmailto:dlacy@search.org  /  http://www.search.org/
[https://outlook.office365.com/owa/service.svc/s/GetFileAttachment?id=AAMkADFhZDVkZmJlLWM5NGUtNGNhZC1iMDMwLWQwMWNhMGE3ZDFlYgBGAAAAAAC%2FIS0CA%2BXdRaRJl6OEu5%2FDBwD4hPlPRqT3RIDfbn0zAPSiAAAAAAENAAD4hPlPRqT3RIDfbn0zAPSiAAAYDupZAAABEgAQALET0TVvCv1InFFAkcmeU2c%3D&X-OWA-CANARY=hhZYOyOQp0KCYeJ48iHFc94GDX02qdAIuBm_mOYLci7zD4ZJxWNQEAj3zF5hlmmHrkfzqIH9EdQ.]http://twitter.com/#!/SEARCHorg  [https://outlook.office365.com/owa/service.svc/s/GetFileAttachment?id=AAMkADFhZDVkZmJlLWM5NGUtNGNhZC1iMDMwLWQwMWNhMGE3ZDFlYgBGAAAAAAC%2FIS0CA%2BXdRaRJl6OEu5%2FDBwD4hPlPRqT3RIDfbn0zAPSiAAAAAAENAAD4hPlPRqT3RIDfbn0zAPSiAAAYDupZAAABEgAQAG3PrqFkki5Oqcqu7sWn2Sk%3D&X-OWA-CANARY=hhZYOyOQp0KCYeJ48iHFc94GDX02qdAIuBm_mOYLci7zD4ZJxWNQEAj3zF5hlmmHrkfzqIH9EdQ.] http://www.facebook.com/SEARCH.org   [https://outlook.office365.com/owa/service.svc/s/GetFileAttachment?id=AAMkADFhZDVkZmJlLWM5NGUtNGNhZC1iMDMwLWQwMWNhMGE3ZDFlYgBGAAAAAAC%2FIS0CA%2BXdRaRJl6OEu5%2FDBwD4hPlPRqT3RIDfbn0zAPSiAAAAAAENAAD4hPlPRqT3RIDfbn0zAPSiAAAYDupZAAABEgAQAFoo8OcFe8BCg9dVe%2F9p7j0%3D&X-OWA-CANARY=hhZYOyOQp0KCYeJ48iHFc94GDX02qdAIuBm_mOYLci7zD4ZJxWNQEAj3zF5hlmmHrkfzqIH9EdQ.] http://www.linkedin.com/groups/SEARCH-National-Consortium-Justice-Information-3251705

**Comment by eric-jahn** [comment]
Diane,
Thanks for your question, and it's a very good one we sort of glossed over.
 It stems from the need to adapt to preexisting vocabularies this
particular community uses, and to shield the extension schema from the
equivalent NIEM terminology.  Also, the other tool out there lets you do
this.  Dropping the "Type" suffix will  a long way, though.

Eric Jahn
Data Architect/IT Director
Alexandria Consulting LLC
St. Petersburg, Florida
727.537.9474
alexandriaconsulting.com

**Comment by eric-jahn** [comment]
Also came up with a second reason, but I'm not sure if it's valid.  I have two different types (say fishing and swimming) in my extension that augment (with a generalization association) nc:ActivityType.  But they each augment different subsets of nc:ActivityType.  So, I guess I'd like to define as a subset "ActivityTypeFishing" with one set of properties from nc:ActivityType, and also "ActivityTypeSwimming" with a different set of properties from nc:ActivityType.  Does this make sense, or am I doing this wrong?

**Comment by CoryCasanave** [comment]
Eric,
I would also love to do this, but it just isn’t NIEM as I understand it. In one IEPD you get one shot at a subset for use by any one exchange due to namespace collision. So while it is clumsy I have tended to either:

·         Define the superset and live with it

·         Define the superset and then RESTRICT it to the intended use (ActivityTypeFishing or ActivityTypeSwimming).
These are NIEM issues, not tool issues. The tools can certainly provide an easier representation of what is possible. For example in the commercial tool we allow a subset schema to narrow a property to a type in an extension schema – this then generates the correct subset schema and a constraint schema to restrict the property.
-Cory Casanave

**Comment by eric-jahn** [comment]
Thank you Cory.  I like the second option (restriction inside two extension types).  I'm actually making an EIEM, defining the universe of acceptable relationships/types in our (sub)domain, from which valid IEPDs may be defined by practitioners.  I can privately discuss the specific community with you, but not on this forum yet.  Okay, I'm feeling more confident about the bounds of the task here, thanks again!

**Comment by dlacy27** [comment]
Let's have a discussion on this...timely, because I'm trying to do the same thing without compromising design practices or over-engineering the extension schema.

Maybe a conference call tomorrow?

Diane Lacy
Information Sharing Specialist
SEARCH, The National Consortium for Justice Information and Statistics
(541) 499-8610  /  dlacy@search.orgmailto:dlacy@search.org  /  http://www.search.org/
[https://outlook.office365.com/owa/service.svc/s/GetFileAttachment?id=AAMkADFhZDVkZmJlLWM5NGUtNGNhZC1iMDMwLWQwMWNhMGE3ZDFlYgBGAAAAAAC%2FIS0CA%2BXdRaRJl6OEu5%2FDBwD4hPlPRqT3RIDfbn0zAPSiAAAAAAENAAD4hPlPRqT3RIDfbn0zAPSiAAAYDupZAAABEgAQALET0TVvCv1InFFAkcmeU2c%3D&X-OWA-CANARY=hhZYOyOQp0KCYeJ48iHFc94GDX02qdAIuBm_mOYLci7zD4ZJxWNQEAj3zF5hlmmHrkfzqIH9EdQ.]http://twitter.com/#!/SEARCHorg  [https://outlook.office365.com/owa/service.svc/s/GetFileAttachment?id=AAMkADFhZDVkZmJlLWM5NGUtNGNhZC1iMDMwLWQwMWNhMGE3ZDFlYgBGAAAAAAC%2FIS0CA%2BXdRaRJl6OEu5%2FDBwD4hPlPRqT3RIDfbn0zAPSiAAAAAAENAAD4hPlPRqT3RIDfbn0zAPSiAAAYDupZAAABEgAQAG3PrqFkki5Oqcqu7sWn2Sk%3D&X-OWA-CANARY=hhZYOyOQp0KCYeJ48iHFc94GDX02qdAIuBm_mOYLci7zD4ZJxWNQEAj3zF5hlmmHrkfzqIH9EdQ.] http://www.facebook.com/SEARCH.org   [https://outlook.office365.com/owa/service.svc/s/GetFileAttachment?id=AAMkADFhZDVkZmJlLWM5NGUtNGNhZC1iMDMwLWQwMWNhMGE3ZDFlYgBGAAAAAAC%2FIS0CA%2BXdRaRJl6OEu5%2FDBwD4hPlPRqT3RIDfbn0zAPSiAAAAAAENAAD4hPlPRqT3RIDfbn0zAPSiAAAYDupZAAABEgAQAFoo8OcFe8BCg9dVe%2F9p7j0%3D&X-OWA-CANARY=hhZYOyOQp0KCYeJ48iHFc94GDX02qdAIuBm_mOYLci7zD4ZJxWNQEAj3zF5hlmmHrkfzqIH9EdQ.] http://www.linkedin.com/groups/SEARCH-National-Consortium-Justice-Information-3251705

**Comment by mehravi1** [comment]
Eric

Cory and I are also working on a couple of projects where we are leveraging
EIEM concept with the ability to generate IEPDs from the EIEM.  I think a
sidebar discussion would be good.

**Comment by eric-jahn** [comment]
Vijay,
This sounds interesting.  Yes, I'd be interested in participating in an
EIEM discussion with you, Cory, and others.  We're seeing NIEM PIM UML as a
great way to define minimal, yet flexible interoperability across loosely
associated software providers.  Eric

**Comment by CoryCasanave** [comment]
Yes, you can use “NIEMName”.
-Cory

**Comment by eric-jahn** [comment]
Cory, 
Just to clarify, from the example above, where an option is to "Define the superset and then RESTRICT it to the intended use (ActivityTypeFishing or ActivityTypeSwimming)", what would be the NIEM UML compliant way to do that?  Could it be by, within the extension schema, appending a <<restriction>> stereotype to an association leading from ActivityTypeFishing and pointing toward the ActivityType class from the subset schema?  And then list the subset of properties I want to retain in ActivityTypeFishing?  Thank you!  -Eric

**Comment by aowen** [comment]
Yes, great point Cory – I forgot about the option to use NIEMName.

Eric and others – in order to get access to the NIEMName attribute, you need to apply the <<ReferenceName>> stereotype to the class and populate NIEMName with the proper NIEMName (PersonType, ActivityType, etc); this will ensure proper schema output should you choose to change the name of the UML Class.  To do this, select the class, go to properties, select the profile tab, and press the green plus sign to see a list of available stereotypes, choose Reference Name.

One caveat here though – if you alter the name of the NIEM class, you’ll no longer be able to use the “update subset” feature for that class.  This is an item we’ve put on the backlog and hope to address soon.

Thanks,
-Andrew
916.215.3933

**Comment by eric-jahn** [comment]
Andrew and Cory,
Thank you for the pointer to use NIEMName, as well as thorough
instructions.  This should work well.  Now, if I can determine the correct
notation to specify a further subset restriction of a NIEM subset class
(the ActivityTypeFishing/ActivityTypeSwimming differentiation question), I
think I'll be able to complete my current modeling task.  Thank you! -Eric

Eric Jahn
Data Architect/IT Director
Alexandria Consulting LLC
St. Petersburg, Florida
727.537.9474
alexandriaconsulting.com

**Comment by timezra** [comment]
We now recognize NIEMName to resolve subset elements with reference library elements. Also, the 'Type' suffix is optional in both NIEMName and the UML element name.

**Comment by eric-jahn** [comment]
excellent, thank you!

Eric Jahn
Data Architect/IT Director
Alexandria Consulting LLC
St. Petersburg, Florida
727.537.9474
alexandriaconsulting.com
